FEAT: BDBD-231 메인리스트 페이지 만들기
FakeDevelopers/DDangDDangMarket_FE pull request #10
Opened 2022-05-24 07:33 UTC by beomdong

### 개요
- 메인 리스트 페이지 만들기

### 변경사항
- `App.vue`에 있었던 글쓰기, firebase 시험 컴포넌트 잠시 지움, `MainScreen.vue`이름 `HeaderScreen.vue`로 변경 및 리펙토링 css폴더 만들고 css초기화 가져와서 import
- `HeaderScreen.vue`의 원래있던 로그인버튼 맨 오른쪽으로 옮기고 상품리스트 router-link태그 추가
- api를 관리할 api 폴더, `index.js` 파일 생성
- `router`를 관리할 routes폴더, `index.js` 파일 생성
- `store`의 `index.js`에 state, mutations, actions 기능, 데이터 추가
- `main.js`에 router 적용
- package 추가
- view 폴더 만들고 상품 리스트를 보여주는 `ProductView.vue` 파일을 생성, 라우터 연결.
- 상품리스트 api 불러와서 뿌려주게 만듬, 페이징구현, `dayjs` 라이브러리를 이용해 타이머 구현
- `WriteScreen.vue` 글쓰기 컴포넌트에서 아직 안고쳐진 for문 깔끔하게 변경
### 관련 지라 및 위키 링크
- [BDBD-231](https://fake-developers.atlassian.net/jira/software/projects/BDBD/boards/10?selectedIssue=BDBD-231)
### 리뷰어에게 하고 싶은 말
- 회의때 말한 새로운 pr 방식을 도입하려고 nodejs 서버를 만들고 거기에 실행을 하는데 api를 계속 local호스트로 불러왔고 결국 방법을 찾지 못해서 아쉬웠다..

2022-05-24 07:43 UTC, konempty commented
![Screenshot_20220524-164332_Samsung Internet](https://user-images.githubusercontent.com/44064530/169976667-ffaf1409-35f7-4807-ac39-dfe18f866a5e.jpg)
버그가 있다고 하네요 ㅠㅠ

2022-05-24 07:47 UTC, konempty approved these changes
고생하셨습니다! 크게 리뷰드릴내용은 없고 파일끝 개행관련 인텔리제이 설정 한번만 확인부탁드릴게요ㅋㅋㅋ 그것만 아니면 저는 머지 승인합니다!

2022-05-24 07:47 UTC, konempty commented on src/api/index.js
> +export { fetchList }
파일 끝 개행이 없네요! 인텔리제이 설정 확인부탁드릴게요!

2022-05-24 08:31 UTC, minseonglove requested changes
일단 이정도

2022-05-24 08:31 UTC, minseonglove commented on src/api/index.js
> +export { fetchList }
다른 api 호출도 여기 다 포함해주십시오

2022-05-24 08:31 UTC, minseonglove commented on src/views/ProductView.vue
> +  user-select: none;
이건 무슨 역할이야

2022-05-24 08:31 UTC, minseonglove commented on src/views/ProductView.vue
> +li:hover:not(.selected-page) {
이건 좋다

2022-05-24 08:31 UTC, minseonglove commented on src/views/ProductView.vue
> +          만료 날짜: {{product.expirationDate}}
분명히 필요 없다고 말했을텐데 말이야

2022-05-24 08:31 UTC, minseonglove commented on src/views/ProductView.vue
> +      return (this.startPoint -1) + 1
?!

2022-05-24 08:31 UTC, minseonglove commented on src/views/ProductView.vue
> +  grid-template-rows: repeat(5,300px);
부운명히 한줄에 3개로 해달라고 했는데 말이야

2022-05-24 08:31 UTC, minseonglove commented on src/views/ProductView.vue
> +  padding: 0;
list-style: none;
padding: 0;
없어도 똑같이 돌아감

2022-05-24 08:31 UTC, minseonglove commented on src/views/ProductView.vue
> +        this.$store.dispatch("FETCH_LIST",this.currentPage)
현재 코드 3줄이 반복되는데 메소드화 하는게 좋아뵘

2022-05-24 08:31 UTC, minseonglove commented on src/views/ProductView.vue
> +      return units
range 메소드로 간지나게 표현 가능합니다.
https://ko.code-paper.com/javascript/examples-make-array-from-number-range-js

2022-05-24 08:31 UTC, minseonglove commented on src/css/reset.css
> +    content: none;
속성이 중복됐어 둘 중 하난 없어야 해

2022-05-24 08:31 UTC, minseonglove commented on src/css/reset.css
> +    font: inherit;
font, font-size 중 하나를 없애야 함

2022-05-24 08:31 UTC, minseonglove commented on src/views/ProductView.vue
> +      return dayjs(expiration).fromNow()
이것만 봐선 시간이 실시간으로 반영이 안되고 있을 것 같아
그리고 남은 시간에 따른 표시 방식을 다 정의 해줘야 해
ex)
* 3시간 이하 -> 시간, 분 표시
* 5분 이하 -> 분, 초 표시

2022-05-24 08:37 UTC, minseonglove commented on src/views/ProductView.vue
> +  padding: 0;
margin도 한 곳에만 주는거면
margin-top이 더 좋겠지요

2022-05-24 08:48 UTC, konempty commented on src/views/ProductView.vue
> +  grid-template-rows: repeat(5,300px);
웹은 화면이 크니까 5개 정도가 맞지않을까요? @minseonglove

2022-05-24 09:14 UTC, beomdong commented on src/views/ProductView.vue
> +  user-select: none;
https://19-97.tistory.com/130
이 글을 참고해서 페이징을 만들었는데 드래그 막기 역할을 하는듯. 왜 막는지는 모르겠고 그대로 가져오다가 린트에러 나는거 있어서 그거 지우다가 저렇게 된거같음.. 지워도 동작은 제대로 하는거같으니 지우겠습니다.

2022-05-24 09:15 UTC, beomdong commented on src/views/ProductView.vue
> +          만료 날짜: {{product.expirationDate}}
수정 완료

2022-05-24 09:16 UTC, beomdong commented on src/views/ProductView.vue
> +      return (this.startPoint -1) + 1
수정 완료

2022-05-24 09:17 UTC, beomdong commented on src/css/reset.css
> +    content: none;
수정 완료

2022-05-24 09:17 UTC, beomdong commented on src/css/reset.css
> +    font: inherit;
수정 완료

2022-05-24 10:07 UTC, minseonglove commented on src/views/ProductView.vue
> +  grid-template-rows: repeat(5,300px);
> 웹은 화면이 크니까 5개 정도가 맞지않을까요? @minseonglove

우리는 일반 거래글과는 달리 보여줘야할 정보가 많읍니다.
그렇기 때문에 한 줄에 3개만 보여주되 상품 칸의 크기를 키우는 방향으로 생각하고 있읍니다.

2022-05-24 15:47 UTC, beomdong commented on src/api/index.js
> +export { fetchList }
수정 완료

2022-05-24 15:49 UTC, beomdong commented on src/views/ProductView.vue
> +        this.$store.dispatch("FETCH_LIST",this.currentPage)
각기 미묘하게 달라서 어떻게 메소드화할지 막막합니다..

2022-05-25 00:06 UTC, beomdong commented on src/views/ProductView.vue
> +      return units
range 메소드 사용, 가격에 콤마 집어넣기 완료

2022-05-25 00:59 UTC, konempty commented
커밋메시지에 각 커밋에 어떤내용을 작업했는지 적어주세요!  전부 통일 시켜버리니 알아보기가 힘드네요 ㅋㅋㅋㅋ

2022-05-25 01:00 UTC, konempty commented on src/App.vue
> +</style>
허허.. 파일끝 개행이 왜 안될까요??ㅋㅋㅋ 엔텔리제이 설정좀 봐주세요 ㅋㅋㅋㅋ

2022-05-25 01:08 UTC, minseonglove requested changes
요정도

2022-05-25 01:08 UTC, minseonglove commented on src/App.vue
> +</style>
개행추가

2022-05-25 01:08 UTC, minseonglove commented on src/api/index.js
> +export { fetchList, submitAccount ,submitWrite }
개행추가

2022-05-25 01:08 UTC, minseonglove commented on src/views/ProductView.vue
> +          past: "%s 지남",
past에 기간 만료를 넣으면 section 태그 하나를 더 안써도 되지 않을카

2022-05-25 01:08 UTC, minseonglove commented on src/views/ProductView.vue
> +        this.$store.dispatch("FETCH_LIST",this.currentPage)
어떤 부분이 메소드화 하기 애매한지 까톡을 주도록

2022-05-25 01:08 UTC, minseonglove commented on src/views/ProductView.vue
> +      return Array(end - start + 1).fill().map((_, idx) => start + idx)
좋다

2022-05-25 01:20 UTC, beomdong commented on src/App.vue
> +</style>
아 다음 수정사항부턴 작업내용 넣겠습니다.. 다시 설정해서 커밋했습니다.

2022-05-25 02:12 UTC, minseonglove commented on package.json
> +    "bootstrap": "^5.1.3",
이건 어디에 사용하는 라이브러리 인가요

2022-05-25 03:39 UTC, beomdong commented on package.json
> +    "bootstrap": "^5.1.3",
페이징 구현할때 알아본 라이브러리인데 설치하고 안지웠네요 지우겠습니다.

2022-05-25 04:06 UTC, minseonglove commented on src/views/ProductView.vue
> +          yy: "%d 년"
최대 기간이 3일이기 때문에
future, 달, 년은 쓰지 않아

2022-05-25 04:12 UTC, minseonglove commented on src/views/ProductView.vue
> +          dd: "%d 일",
d와 dd의 차이가 뭔지 알랴줄 수 있니

2022-05-25 04:31 UTC, beomdong commented on src/views/ProductView.vue
> +          yy: "%d 년"
달,년은 지워도 문제 없었는데 future은 지우면 에러가 떠서 남겼습니다..

2022-05-25 04:34 UTC, beomdong commented on src/views/ProductView.vue
> +          dd: "%d 일",
1일 정도 남았을때는 a days ago 로 표현하고 며칠정도 남았는지는  4 days ago 이런식으로 표현하려고 한듯

2022-05-25 05:24 UTC, minseonglove commented on src/views/ProductView.vue
> +          dd: "%d 일",
그럼 d를 정의 하지 않고 1일 남았을 때는 dd의 포맷으로 가니

2022-05-25 05:59 UTC, beomdong commented on src/views/ProductView.vue
> +          dd: "%d 일",
d를 정의안하면 에러가 뜨네.

2022-05-25 12:27 UTC, beomdong commented on src/views/ProductView.vue
> +      return dayjs(expiration).fromNow()
5분이하는 눈으로 확인하기가 좀 어려워서 30분으로 잡았음

2022-05-25 13:11 UTC, minseonglove requested changes
현재 테스트 결과 타이머가 다음 페이지로 넘어가도 중지되지 않고 계속 돌아감
매우 매우 중대한 문제니 해결 하십시오

2022-05-25 13:11 UTC, minseonglove commented on src/components/TimerScreen.vue
> +   <section v-show="!countdownCheck(countdown)">남은시간: {{millisToMinutesAndSeconds(countdown)}}</section>
혹시 왜 두 개 있는지 알랴줄 수 있니

2022-05-25 13:11 UTC, minseonglove commented on src/views/ProductView.vue
> +        </section>
하나의 태그로 처리 가능해 보임

2022-05-25 13:42 UTC, beomdong commented on src/components/TimerScreen.vue
> +   <section v-show="!countdownCheck(countdown)">남은시간: {{millisToMinutesAndSeconds(countdown)}}</section>
원래 3시간이하, 30분 이상이면 시간,  분 보여주고
30분 이하면 분, 초 보여주려고 했음.. 그 이상은 상품리스트 쪽에서 처리하도록 했는데 반응형이 적용안되서 고쳐야하고

2022-05-25 14:06 UTC, konempty commented on src/components/TimerScreen.vue
> +   <section v-show="!countdownCheck(countdown)">남은시간: {{millisToMinutesAndSeconds(countdown)}}</section>
`원래 3시간이하, 30분 이상이면` 이라면 0시간 35분 이렇게도 뜰수 있다는걸까요?

2022-05-25 14:13 UTC, beomdong commented on src/components/TimerScreen.vue
> +   <section v-show="!countdownCheck(countdown)">남은시간: {{millisToMinutesAndSeconds(countdown)}}</section>
넵..

2022-05-25 14:18 UTC, konempty commented on src/components/TimerScreen.vue
> +   <section v-show="!countdownCheck(countdown)">남은시간: {{millisToMinutesAndSeconds(countdown)}}</section>
ㅋㅋㅋㅋㅋ 제 개인적인 취향이지만 0시간은 예쁘지 않은것 같아요!

2022-05-30 08:37 UTC, minseonglove requested changes

2022-05-30 08:37 UTC, minseonglove commented on src/components/TimerScreen.vue
> +   </section>
html에서 분기하지 말고 메소드 안에서 분기 하십시오

2022-05-30 08:37 UTC, minseonglove commented on src/components/TimerScreen.vue
> +    },
expirationCheck는 한 곳에만 쓰이고
dayjs(expiration).diff(this.currentDate) > 0
이렇게 한 줄로 처리가 가능해
그래서 메소드화할 필요가 없어보여

2022-05-30 08:37 UTC, minseonglove commented on src/components/TimerScreen.vue
> +        this.countdown = dayjs(expiration).valueOf() - dayjs().valueOf()
매 초마다 dayjs(expiration).valueOf()를 계산하는건 비효율적이야

2022-05-30 08:37 UTC, minseonglove commented on src/views/ProductView.vue
> +      }
조건문은 없는게 깔끔해 보여

2022-05-30 08:54 UTC, minseonglove commented on src/components/TimerScreen.vue
> +      if(this.stopTimer){ // 타이머 멈추기: 중복으로 타이머가 돌아가는걸 방지
혹시 이거 동작 하는지 확인해보셨습니까

2022-05-30 14:12 UTC, beomdong commented on src/components/TimerScreen.vue
> +      if(this.stopTimer){ // 타이머 멈추기: 중복으로 타이머가 돌아가는걸 방지
이거 넣었을때 타이머가 중복으로 돌아가지 않았습니다.

2022-06-01 12:36 UTC, konempty commented on src/components/TimerScreen.vue
> +        return '기간만료'
사족이긴 한데 이런 문구를 i18n에 대응할수있도록 작성하면 어떨까요?

2022-06-01 12:43 UTC, konempty commented on src/components/TimerScreen.vue
> +      return minute *60 *1000
*60 이거 붙어있는거 불-편하네요ㅋㅋㅋㅋ vue에서는 포매팅 지원이 안될까요? 된다면 전체파일 포매팅 부탁드릴게요!ㅋㅋㅋㅋ

2022-06-01 12:47 UTC, konempty commented on src/components/TimerScreen.vue
> +      return expiration <= this.minuteToMillis(30) && expiration>0
this.minuteToMillis(30) 이 코드는 항상 같은 값을 리턴하지 않을까요?ㅋㅋㅋㅋㅋ 상수로 정해두면 좋을것 같아요!

2022-06-01 12:59 UTC, konempty commented on src/components/TimerScreen.vue
> +      return expiration <= this.hourToMillis(3) && this.countdown > this.minuteToMillis(30)
```this.countdown > this.minuteToMillis(30)``` 요 코드는
 ```expiration >= this.hourToMillis(1)``` 이렇게 하면

```
if(this.hourBool){ 
    const hours = Math.floor((millis / (60 * 60000))%24)
    const minutes = Math.floor((millis / 60000) % 60)
    return (hours!==0? hours + '시간' : '') + (minutes!==0? minutes + '분' : '')
 }
```

이코드가 
```
if(this.hourBool){ 
    const hours = Math.floor((millis / (60 * 60000))%24)
    const minutes = Math.floor((millis / 60000) % 60)
    return hours + '시간' : '' + (minutes!==0? minutes + '분' : '') 
}
```

이렇게 간단해질수 있지 않을까요?
물론 60분 미만 남았을때 코드도 수정해야겠죠?ㅋㅋㅋㅋㅋ

2022-06-01 13:01 UTC, beomdong commented on src/components/TimerScreen.vue
> +      return expiration <= this.hourToMillis(3) && this.countdown > this.minuteToMillis(30)
차근차근 고쳐보겠습니다

2022-06-01 13:04 UTC, beomdong commented on src/components/TimerScreen.vue
> +      return minute *60 *1000
수정완료

2022-06-01 13:13 UTC, beomdong commented on src/components/TimerScreen.vue
> +      return expiration <= this.minuteToMillis(30) && expiration>0
나머지 숫자들도 다 상수로 정하면 될까요?

2022-06-01 13:36 UTC, konempty commented on src/components/TimerScreen.vue
> +      return expiration <= this.minuteToMillis(30) && expiration>0
그건 스스로 판단해보시면 좋을것 같네요!ㅋㅋㅋㅋ

2022-06-01 16:33 UTC, beomdong commented on src/components/TimerScreen.vue
> +        return '기간만료'
작성 완료

2022-06-02 10:58 UTC, minseonglove approved these changes
통과

2022-06-02 10:58 UTC, minseonglove commented on src/views/ProductView.vue
>        let end = this.startPage + this.pageCount -1
JSHint를 활용해보십시오

2022-06-02 13:47 UTC, creatorbegg approved these changes

2022-06-02 13:57 UTC, merged