Feature/bdbd 279
FakeDevelopers/DDangDDangMarket_FE pull request #13
Opened 2022-06-05 03:49 UTC by beomdong

### 개요
- nodejs 연결

### 변경사항
- express.js 백엔드 폴더 생성, 프로젝트 빌드파일 적용(메인 프로젝트에서 npm run build로 빌드)
- 페이징 알고리즘 약간 수정 
- 백엔드 폴더 빌드(백엔드 폴더에서 npm run build)
### 관련 지라 및 위키 링크
- [BDBD-279](https://fake-developers.atlassian.net/jira/software/projects/BDBD/boards/10?selectedIssue=BDBD-279)
### 리뷰어에게 하고 싶은 말
- 서버 돌아가는건 성공했습니다.. 부족한부분은 차근차근 고치겠습니다.

2022-06-05 04:38 UTC, konempty commented
> SonarCloud Quality Gate failed.    [![Quality Gate failed](https://camo.githubusercontent.com/4ea51c1f64ee3746f631653a02ab678ca6a3efb5f5cb474402faed2e3dcf90b5/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f6661696c65642d313670782e706e67)](https://sonarcloud.io/dashboard?id=FakeDevelopers_BidderBidder_FE&pullRequest=13)
> 
> [![Bug](https://camo.githubusercontent.com/4c6102327f5a954f9c8acaf2e2714183157a9e41717b371b2cd585cf25057310/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6275672d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_FE&pullRequest=13&resolved=false&types=BUG) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_FE&pullRequest=13&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_FE&pullRequest=13&resolved=false&types=BUG) [![Vulnerability](https://camo.githubusercontent.com/3ba1ee49636ffc3427e38649a9f8a65ee392f28e8a662fcf96ce24cefbb520e9/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f76756c6e65726162696c6974792d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_FE&pullRequest=13&resolved=false&types=VULNERABILITY) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_FE&pullRequest=13&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_FE&pullRequest=13&resolved=false&types=VULNERABILITY) [![Security Hotspot](https://camo.githubusercontent.com/fb735cbe76f8d5e1679c76ce83b740ceb1eaf62de4f7bf88623dc9953261aff7/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f73656375726974795f686f7473706f742d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=FakeDevelopers_BidderBidder_FE&pullRequest=13&resolved=false&types=SECURITY_HOTSPOT) [![E](https://camo.githubusercontent.com/ca3e5c9e7ad5fd04244d2d793976efbe479a024b145a815384556548a9884b5f/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f452d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=FakeDevelopers_BidderBidder_FE&pullRequest=13&resolved=false&types=SECURITY_HOTSPOT) [2 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=FakeDevelopers_BidderBidder_FE&pullRequest=13&resolved=false&types=SECURITY_HOTSPOT) [![Code Smell](https://camo.githubusercontent.com/8fe18b2dfb6f7d4e44582f281b29f617eb5ae07c248d2002ca586e91da219212/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_FE&pullRequest=13&resolved=false&types=CODE_SMELL) [![B](https://camo.githubusercontent.com/ee7f8cac547e3e28ad7e683c451c8caf2f19d70bc37d6bcba574dac8ff86d194/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f422d313670782e706e67)](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_FE&pullRequest=13&resolved=false&types=CODE_SMELL) [18 Code Smells](https://sonarcloud.io/project/issues?id=FakeDevelopers_BidderBidder_FE&pullRequest=13&resolved=false&types=CODE_SMELL)
> 
> [![No Coverage information](https://camo.githubusercontent.com/86785eaa572e061f5ecb3f8bf1cbb7b8eca44925083f92d067805b4362cead0c/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f436f76657261676543686172742f4e6f436f766572616765496e666f2d313670782e706e67)](https://sonarcloud.io/component_measures?id=FakeDevelopers_BidderBidder_FE&pullRequest=13) No Coverage information [![0.0%](https://camo.githubusercontent.com/8047c63e1f9ed03f63001e1eadce4676bade3e0f83ec690a9c625287796248a6/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f4475706c69636174696f6e732f332d313670782e706e67)](https://sonarcloud.io/component_measures?id=FakeDevelopers_BidderBidder_FE&pullRequest=13&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=FakeDevelopers_BidderBidder_FE&pullRequest=13&metric=new_duplicated_lines_density&view=list)

오.. 문제점이 많네요 ㅋㅋㅋㅋ

2022-06-05 06:39 UTC, konempty reviewed
backend/backend-linux 이런 배포 파일은 깃헙에 올리시지 않는게 좋아요

2022-06-05 06:46 UTC, konempty requested changes
크흐 고생하셨습니다 리뷰 확인 부탁드릴게요! 역시 프론트는 저한테는 어렵네요 ㅋㅋㅋㅋ

2022-06-05 06:46 UTC, konempty commented on backend/public/index.html
> +<!DOCTYPE html><html lang=""><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href=
오 이파일은 왜 개행이 없을까요?

2022-06-05 06:46 UTC, konempty commented on src/api/index.js
> +    baseUrl: 'http://3.38.81.213:8080'
원래는 배포 페이즈 별로 백엔드를 따로 봐야 해요 예를 들어 샌박 페이즈에서는 샌박 백엔드, 리얼 페이즈에서는 리얼 서버를 봐야해요. 단 지금은 백엔드에서 관련 개발이 되지않아 의미가 없지만 추후에는 페이즈 별로 분기 가능하게 처리해주세요!

2022-06-05 06:46 UTC, konempty commented on src/views/ProductView.vue
>          this.startPoint=1
파일에 포멧팅이 안된것 같은데 전체 파일 대상으로 포메팅 부탁드릴게요 :)

2022-06-05 06:47 UTC, konempty commented on src/api/index.js
> +    baseUrl: 'http://3.38.81.213:8080'
물론 지금 부터 처리해주시면 더욱좋아요 ㅋㅋㅋㅋㅋ

2022-06-05 07:09 UTC, minseonglove commented
> backend/backend-linux 이런 배포 파일은 깃헙에 올리시지 않는게 좋아요 ![Screenshot_20220605-153936_Samsung Internet](https://user-images.githubusercontent.com/44064530/172038786-56b8c5e5-1aa0-43b6-b3eb-831dc06730e6.jpg)

이런 밤동이

2022-06-06 13:37 UTC, konempty commented on .gitignore
> +/backend/backend-win.exe
이부분은  /backend/ 이라고 쓰면 하위 디렉토리 및 파일이 전부 추가될거예요

2022-06-12 01:49 UTC, minseonglove requested changes
코드 포맷팅을 잘해주었읍니다.
씨큐리티 경고만 수정해주세요

2022-06-12 01:49 UTC, minseonglove commented on src/api/index.js
> +}
별도의 파일로 빼고 그 파일을 ignore하십시오

2022-06-12 01:49 UTC, minseonglove commented on src/views/ProductView.vue
> +          this.startPoint += this.pageCount
이거
this.startPoint = Math.min(this.startPoint + this.pageCount, this.maxPage)
로 줄이면 간지나보이지 않니

2022-06-12 01:49 UTC, minseonglove commented on src/views/ProductView.vue
> +          this.startPoint -= this.pageCount
이것도 Math나 삼항으로 줄일 수 있겠구나

2022-06-12 01:49 UTC, minseonglove commented on vue.config.js
> +        proxy: "http://3.38.81.213:8080"
이건 왜 소나가 머라고 안하지

2022-06-12 01:51 UTC, minseonglove commented on backend/public/index.html
> +<!DOCTYPE html><html lang=""><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href=
> 오 이파일은 왜 개행이 없을까요?

엄청난 최적화를 위해 webpack으로 빌드된 html파일은 개행이 없이 나와용

2022-06-12 04:03 UTC, konempty commented on src/api/index.js
> +}
흐음 요건 브라우저에서 개발자 도구로 보면 다 보이는 값인데 굳이 숨겨야할 필요가 있을까요?ㅋㅋㅋㅋ

2022-06-12 06:54 UTC, minseonglove commented on src/api/index.js
> +}
> 흐음 요건 브라우저에서 개발자 도구로 보면 다 보이는 값인데 굳이 숨겨야할 필요가 있을까요?ㅋㅋㅋㅋ

쏘나한테서  숨겨야해

2022-06-12 08:18 UTC, konempty commented on src/api/index.js
> +}
소나는 IP쓰지 말라고 하지 도메인 쓰지 말라고는 안하지 않나요? ㅋㅋㅋㅋ

2022-06-12 08:59 UTC, beomdong commented on src/api/index.js
> +}
도메인써도 http뒤에 s 붙이라고 경고가 뜨는데 https로 쓰면 api가 안불러와집니다..

2022-06-12 10:50 UTC, minseonglove approved these changes
잘했읍니다

2022-06-12 10:50 UTC, minseonglove commented on src/api/baseUrl.js
> +}
뭐 도메인이니까 괜찮겠지요

2022-06-12 11:34 UTC, konempty approved these changes
고생하셨습니다! 👍

2022-06-12 16:37 UTC, creatorbegg approved these changes

2022-06-14 07:28 UTC, merged