Feature/bdbd 287
FakeDevelopers/DDangDDangMarket_FE pull request #15
Opened 2022-06-18 10:26 UTC by beomdong

### 개요
 - 상품리스트 페이지번호를 url 에 표시해 나타나게 하기
### 변경사항
 - 상품 페이지를 누르면 번호가 url에 표시되도록 함.
 - 타이머 오류가 있어서 수정
### 관련 지라 및 위키 링크
 - [BDBD-287](https://fake-developers.atlassian.net/jira/software/projects/BDBD/boards/10?selectedIssue=BDBD-287)
### 리뷰어에게 하고 싶은 말
 - 토익공부때문에 진행이 많이 느려져서 죄송합니다.

2022-06-20 01:13 UTC, minseonglove approved these changes
잘하였습니다.

2022-06-25 10:58 UTC, creatorbegg approved these changes

2022-06-25 12:24 UTC, konempty requested changes
고생하셨습니다 👍 불필요한 파일만 조금 정리가 되면 좋을것 같아요!

2022-06-25 12:24 UTC, konempty commented on backend/public/js/app.d9c48a12.js
> -//# sourceMappingURL=app.d9c48a12.js.map
backend 하위의 폴더들은 불필요한 파일 아닐까요??

2022-06-26 06:15 UTC, konempty commented
앗 지금보니까 PR제목도 설정이 안되어있네요!

2022-06-26 13:49 UTC, beomdong commented on backend/public/js/app.d9c48a12.js
> -//# sourceMappingURL=app.d9c48a12.js.map
파일을 따로빼고 backend폴더를 아예 뺀채로 commit 할까요?

2022-06-26 13:56 UTC, konempty commented on backend/public/js/app.d9c48a12.js
> -//# sourceMappingURL=app.d9c48a12.js.map
깃이그노어로 처리해주세요! 매번 커밋할때마다 파일을 뺄순없으니까요 ㅋㅋㅋㅋㅋ

2022-06-26 14:16 UTC, konempty commented
지라 링크가 이상하게 잡혀있네요?!

2022-06-26 14:59 UTC, konempty commented
![Screenshot_20220626-235821_Samsung Internet](https://user-images.githubusercontent.com/44064530/175820422-89617648-0133-46dc-b90e-4bca7ac34e9b.jpg)
![Screenshot_20220626-235834_Samsung Internet](https://user-images.githubusercontent.com/44064530/175820427-a898337a-fba6-4fcf-8e94-f119aa779776.jpg)
이거 두개 확인부탁드려요!

2022-06-26 15:00 UTC, konempty requested changes
코멘트로 남긴거 수정부탁드릴게요!

2022-06-26 15:15 UTC, konempty approved these changes
컨플릭트만 수정하고 바로 머지해주세요!

2022-06-26 19:17 UTC, merged