Feature/bdbd 309
FakeDevelopers/DDangDDangMarket_FE pull request #18
Opened 2022-08-06 00:08 UTC by beomdong

### 개요
 - 상품리스트 검색필터기능 추가
### 변경사항
 - 샌드박스에 있던 로그인 모달 디자인 적용
 - 검색창 추가
 - 검색때 나오는 최신검색어, 인기검색어 보여주는 모달 추가
 - 모달움직임 최대한 구현

### 관련 지라 및 위키 링크
 - [BDBD-309](https://fake-developers.atlassian.net/jira/software/projects/BDBD/boards/10?selectedIssue=BDBD-309)
### 리뷰어에게 하고 싶은 말
 - 많이 늦게 pr을 하게되어 죄송합니다.. 현재 작업중 아쉬운 것은 입력을 하다가 다시 다 지웠을 때 자동검색 모달에서 다시 최근,인기 검색어 모달을 표시하게 해주고 싶었는데 잘 안된 것 입니다. 방법이 있다거나 고쳐야 할게 있으면 알려주세요.

2022-08-07 12:36 UTC, konempty approved these changes
고생하셨습니다  👍

2022-08-24 06:13 UTC, minseonglove requested changes
1. 검색 기록이 두 개 이상일 때 가장 위에 있는 검색 기록이 안지워짐
2. 검색어를 드래그하면 포커스가 사라져서 모달도 같이 사라짐 여기서 검색어 입력을 재개해도 검색 결과 모달이 나오지 않음

정규표현식은 이 싸이트에서 테스트 해보면서 만들면 쉬워
https://regexr.com/5mhou

2022-08-24 06:13 UTC, minseonglove commented on src/components/SearchEngine.vue
> +          <h4>최근검색어</h4>
지금은 안해도 되지만 나중에 디자인을 적용할 땐 이런 문자열 리소스들은 locales로 빼야해

2022-08-24 06:13 UTC, minseonglove commented on src/components/SearchEngine.vue
> +      <button @click="searchResult(this.searchText),addKeyword(this.searchText)"> 검색</button>
addKeyword 메소드는 searchResult가 호출될 때만 호출되는 메소드기 때문에 이렇게 분리하기 보단 searchResult 안에 박아 넣는 것도 좋아 보이는구나

2022-08-24 06:13 UTC, minseonglove commented on src/components/SearchEngine.vue
> +        <div class="searchForm" v-if="!getSearchingState">
css 클래스 네이밍 방식이 통일이 안 돼있네
소문자와 하이픈을 쓰는 방식으로 통일해줘 ex) search-form

2022-08-24 06:13 UTC, minseonglove commented on src/components/SearchEngine.vue
> +        <div class="searchForm" v-else-if="getSearchingState">
조건문 상태가 true, false 두 상태기 때문에 v-else가 나아보였는데
이것도 의미가 분명해 보여서 좋네

2022-08-24 06:13 UTC, minseonglove commented on src/components/SearchEngine.vue
> +      const words = /[ㄱ-ㅎㅏ-ㅣ가-힣a-zA-Z]/;
이러면 숫자나 특문이 들어왔을때는 검색 리스트를 뽑아주지 않겠구나

2022-08-24 06:13 UTC, minseonglove commented on src/components/SearchEngine.vue
> +        this.searchingControl(true)
어느 조건이든 modalControl이 true라면 조건문 밖으로 빼는게 이뻐보여

2022-08-24 06:13 UTC, minseonglove commented on src/components/SearchEngine.vue
> +        this.searchingControl(true)
위에 modalChange 메소드를 활용하면 이쁘게 떨어지겠구나

2022-08-24 06:13 UTC, minseonglove commented on src/components/SearchEngine.vue
> +$width: 582px;
이건 무엇이지

2022-08-24 06:13 UTC, minseonglove commented on src/store/index.js
> +        if (localStorage.length > 0) {
이게 없어도 length가 0이면 for문이 안 돌아갈테야

2022-08-24 06:24 UTC, beomdong commented on src/components/SearchEngine.vue
> +$width: 582px;
scss 변수기능인데 검색창 넓이를 저렇게 밖에다 빼줘서 모달넓이랑 똑같이 통일하게 했음

2022-11-05 13:33 UTC, minseonglove requested changes
딱 이번만 더 수정하면 되겠다

2022-11-05 13:33 UTC, minseonglove commented on src/components/SearchEngine.vue
> +          <ul v-if="getAutoWordsState">
getSearchingState가 true이지만 getAutoWordsState가 false인 경우도 있니

2022-11-05 13:33 UTC, minseonglove commented on src/components/SearchEngine.vue
> +      }
조건문을 그대로 매개변수로 넣어주면 되겠지

2022-11-05 13:33 UTC, minseonglove commented on src/components/SearchEngine.vue
> +    }
잘했어

2022-11-05 13:33 UTC, minseonglove commented on src/components/SearchEngine.vue
> +    },
지금은 빈 문자열만 걸러내고 있는데 단순히 공백만 있는 문자열은 저장에서 제외하고 (물론 api도 호출안하는게 좋겠지) 문자열을 저장할 때는 양쪽 끝에 붙은 무의미한 공백을 제거하는 동작도 필요하겠어 ('밤동이' == '밤동이 ')

2022-11-05 13:33 UTC, minseonglove commented on src/components/SearchEngine.vue
> +      }
이것도 조건문을 매개변수에 넣자

2022-11-05 13:33 UTC, minseonglove commented on src/components/SearchEngine.vue
> +    },
이게 뭐시야

2022-11-05 13:33 UTC, minseonglove commented on src/components/SearchEngine.vue
> +        this.showButtonControl(false)
위에 정의한 clearAllHistory를 활용하면 되겠군

2022-11-05 13:33 UTC, minseonglove commented on src/store/index.js
> +                    localStorage.setItem("searchHistory", JSON.stringify(state.searchHistory));
if든 else든 하는 동작이라면 조건문 밖으로 빼는게 맞아

2022-11-05 13:33 UTC, minseonglove commented on src/store/index.js
> +                localStorage.setItem("searchHistory", JSON.stringify(state.searchHistory));
searchHistory를 비운 이후의 동작으로는 적절치 않아 뵈네

2022-11-05 13:33 UTC, minseonglove commented on src/store/index.js
> +                    let idx = searchHistory.indexOf(words)
indexOf만으로 searchHistory에 words가 있는지를 판단할 수 있어

2022-11-05 13:33 UTC, minseonglove commented on src/components/SearchEngine.vue
> +        searchWord: words,
api 호출 시작전에 words를 검증해서 적절치 않다면 api를 수행안하고 넘어가도 될테야

2022-11-09 06:33 UTC, beomdong commented on src/components/SearchEngine.vue
> +          <ul v-if="getAutoWordsState">
getAutoWordsState 살펴보니 필요없는거같아서 지워버렸음

2022-11-09 06:33 UTC, beomdong commented on src/components/SearchEngine.vue
> +      }
이것도 필요없는거같아서 지움

2022-11-09 06:34 UTC, beomdong commented on src/components/SearchEngine.vue
> +    },
지우고 집적 false 반환하도록 바꿈

2022-11-09 06:36 UTC, beomdong commented on src/components/SearchEngine.vue
> +        this.showButtonControl(false)
반영 완료

2022-11-09 08:01 UTC, beomdong commented on src/store/index.js
> +                    localStorage.setItem("searchHistory", JSON.stringify(state.searchHistory));
반영 완료

2022-11-09 08:01 UTC, beomdong commented on src/store/index.js
> +                localStorage.setItem("searchHistory", JSON.stringify(state.searchHistory));
일단 조건문밖으로 뺌

2022-11-09 11:05 UTC, beomdong commented on src/components/SearchEngine.vue
> +      }
반영 완료

2022-11-09 12:26 UTC, beomdong commented on src/components/SearchEngine.vue
> +    },
반영 완료

2022-11-09 14:58 UTC, beomdong commented on src/components/SearchEngine.vue
> +          <ul v-if="getAutoWordsState">
필요없는줄 알았는데 특수문자인 공백문자로 이루어져있으면 getSearchingState는 true 지만 getAutoWordsState가 false가 되어 자동검색어가 안보이도록 했음

2022-11-09 14:59 UTC, beomdong commented on src/components/SearchEngine.vue
> +      }
매개변수로 넣고 공백특수문자만 있어도 false 되게 함

2022-11-09 15:00 UTC, beomdong commented on src/store/index.js
> +                    let idx = searchHistory.indexOf(words)
반영 완료

2022-11-09 15:00 UTC, beomdong commented on src/components/SearchEngine.vue
> +        searchWord: words,
반영 완료

2022-11-11 04:38 UTC, minseonglove approved these changes
![yQoeObI](https://user-images.githubusercontent.com/90435036/201264379-c434da84-1ab2-4ab8-8be0-4bf0d74b790b.gif)

2022-11-11 11:32 UTC, creatorbegg approved these changes
수고하셨습니다!
이미 구조적인 부분은 리뷰를 너무 잘 해주셔서 저는 다른 부분을 위주로 살펴봤습니다.

저는 UX적인 부분인데요, 몇가지 제안 드리고 싶은게 있습니다.
아래 내용 참고해주세요 :)

- 지금 샌드박스 기준으로 검색창에 입력 시, 입력한 텍스트와 관련 없는 리스트가 출력되고 있는데 이 부분은 혹시 백엔드 쪽 이슈일까요? (예시: a 입력시 test1이 보여짐)
- 개인적으로 검색시 URL에 검색어가 파라미터로 제공되는게 어떨까 싶습니다. 지금은 검색하면 바로 api 요청 날려서 새로고침 없이 불러오는건 좋은데, 새로고침을 하면 그냥 메인페이지로 이동해버려서요. 검색시 검색어를 url에 남겨두고, 새로고침해도 그 url에서 우선적으로 파라미터 값 가져와서 검색 돌리는게 어떨까 싶습니다.
- - 사용자가 새로운 글을 보기위해 새로고침을 하는 액션도 라이브에서 충분히 일어날 수 있는 시나리오라고 생각해서요.
- - 참고자료로, 네이버 검색에서 "구글" 부분에 다른거 입력하면 그 바꾼 키워드로 검색되는 방식입니다. ( https://search.naver.com/search.naver?where=nexearch&sm=top_hty&fbm=1&ie=utf8&query=구글 )

2022-11-11 11:36 UTC, beomdong commented
> 수고하셨습니다! 이미 구조적인 부분은 리뷰를 너무 잘 해주셔서 저는 다른 부분을 위주로 살펴봤습니다.
> 
> 저는 UX적인 부분인데요, 몇가지 제안 드리고 싶은게 있습니다. 아래 내용 참고해주세요 :)
> 
> * 지금 샌드박스 기준으로 검색창에 입력 시, 입력한 텍스트와 관련 없는 리스트가 출력되고 있는데 이 부분은 혹시 백엔드 쪽 이슈일까요? (예시: a 입력시 test1이 보여짐)
> * 개인적으로 검색시 URL에 검색어가 파라미터로 제공되는게 어떨까 싶습니다. 지금은 검색하면 바로 api 요청 날려서 새로고침 없이 불러오는건 좋은데, 새로고침을 하면 그냥 메인페이지로 이동해버려서요. 검색시 검색어를 url에 남겨두고, 새로고침해도 그 url에서 우선적으로 파라미터 값 가져와서 검색 돌리는게 어떨까 싶습니다.
> * * 사용자가 새로운 글을 보기위해 새로고침을 하는 액션도 라이브에서 충분히 일어날 수 있는 시나리오라고 생각해서요.
> * * 참고자료로, 네이버 검색에서 "구글" 부분에 다른거 입력하면 그 바꾼 키워드로 검색되는 방식입니다. ( [https://search.naver.com/search.naver?where=nexearch&sm=top_hty&fbm=1&ie=utf8&query=구글](https://search.naver.com/search.naver?where=nexearch&sm=top_hty&fbm=1&ie=utf8&query=%EA%B5%AC%EA%B8%80) )

2022-11-11 15:14 UTC, minseonglove commented
@creatorbegg 
> 지금 샌드박스 기준으로 검색창에 입력 시, 입력한 텍스트와 관련 없는 리스트가 출력되고 있는데 이 부분은 혹시 백엔드 쪽 이슈일까요? (예시: a 입력시 test1이 보여짐)

얘는 현재 검색어 자동완성 api가 없어서 그래
나머지 제안은 다 좋은 말이야

2022-11-12 10:37 UTC, merged