Feature/BDBD-388 로그인 모달 디자인
FakeDevelopers/DDangDDangMarket_FE pull request #20
Opened 2022-08-19 13:53 UTC by creatorbegg

### 개요
- 로그인 모달의 디자인을 작업했습니다
### 변경사항
- AlertModule을 로그인 모달로 사용했습니다.
- 디자인 적용되었습니다.
### 관련 지라 및 위키 링크
[BDBD-388](https://fake-developers.atlassian.net/browse/BDBD-388?atlOrigin=eyJpIjoiYTFkZDM1M2QzZTY0NGIwZTgyMjFlZDk5MWVmMGEwZWIiLCJwIjoiaiJ9)
### 리뷰어에게 하고 싶은 말
PR이 좀 늦어서 죄송합니다 ㅠㅠ 디자인은 추후 컴포넌트화하고 리팩토링이 필요할 것으로 보입니다.

2022-08-21 11:53 UTC, konempty approved these changes
크흐 고생하셨습니다  👍

2022-08-21 13:15 UTC, beomdong approved these changes
수고하셨습니다. 코드스멜 남은건 어쩔 수 없는건지 궁금하네요

2022-08-24 05:50 UTC, minseonglove requested changes
좋아좋아
디자인 최종 승인 받고
리뷰 반영해서 다시 요청 보내줘

2022-08-24 05:50 UTC, minseonglove commented on src/components/common/AlertModal.vue
> +            </a>
이 로그인 버튼들은 컴포넌트화 하긴 해야겠다
중복 태그가 많네

2022-08-24 05:50 UTC, minseonglove commented on src/components/common/AlertModal.vue
> +      background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='46' height='46'%3E%3Cdefs%3E%3Cfilter x='-50%25' y='-50%25'
요 이미지 리소스 정보도 별도로 파일을 만들어서 보관하는게 이뻐보이겠다

2022-09-03 10:57 UTC, minseonglove approved these changes

2022-09-03 10:58 UTC, merged