FEAT: BDBD-165 로그인버튼 post전송, 응답 받아오는 기능추가
FakeDevelopers/DDangDDangMarket_FE pull request #7
Opened 2022-04-15 17:05 UTC by beomdong

### 개요
- 모달안에 정보를 입력하고 로그인버튼을 누르면 목업 api로 요청을 보내는 기능을 추가
### 변경사항
- 기존 `MainScreen.vue`의 데이터이름을 목업 api에 요청할 양식에 맞춰 username -> email, password -> passwd 로 바꿈
- `MainScreen.vue`의 form 태그에 트리거 속성 추가하고 밑에 언급하는 메서드에 연결
- `MainScreen.vue`의 method에 `summitForm` 메서드를 추가 (axios로 목업 api에 요청을 하는 메서드)
- `vue.config.js` 파일의 devServer의 proxy를 목업 api 주소로 바꿈.
### 관련 지라 및 위키 링크
[https://fake-developers.atlassian.net/jira/software/projects/BDBD/boards/10?selectedIssue=BDBD-165](url)
### 리뷰어에게 하고 싶은 말
많이 부족하다는 것을 다시 느꼈습니다..

2022-04-16 01:04 UTC, konempty approved these changes
굿굿 제가 드릴 리뷰는 없네요 👍 
https://github.com/FakeDevelopers/BidderBidder_FE/security/dependabot 여기 보시면 라이브러리에 문제가 있다고 하네요 확인해보시고 다음에 적용해주세요!

2022-04-16 01:06 UTC, konempty requested changes
지금보니까 컨플릭트가 났네요! 저번거 머지하시고 pull안당기신것 같아요! 컨플릭트 해결해주세요!

2022-04-16 01:45 UTC, konempty commented
지라 링크를 달때는
 [지라]/(URL) 중간에 슬래시빼고 이렇게 달아주세요
그러면 [지라](google.com) 이렇게 보여요
그리고 리뷰어에게 하고싶은말에는 대시를 안붙히셨네요 추가 부탁드릴게요!

2022-04-16 02:11 UTC, konempty commented
커밋메시지에서 수정사항이 많아보이는데 제목만있고 내용은 안적어 두셨네요 다음부터는 변경사항이 여러개 이면 내용도 채워주세요!

2022-04-16 14:55 UTC, konempty approved these changes
굿굿 수고하셨습니다! 바로 머지하셔도 될듯합니다!

2022-04-17 06:41 UTC, minseonglove requested changes
수정할 때 Readme도 같이 수정해서 커밋해주세요

2022-04-17 06:41 UTC, minseonglove commented on src/components/MainScreen.vue
>            })
https://www.crocus.co.kr/1767
https://daep93.tistory.com/7

axios 요청 메소드를 async await 방식으로 수정해보세요

2022-04-17 07:38 UTC, minseonglove approved these changes
잘해냈읍니다

2022-04-17 10:03 UTC, creatorbegg approved these changes

2022-04-17 10:57 UTC, merged